### ISSUE TITLE
Warning on VS Code

### ISSUE THREAD

**Issue by Navaneethp007** [Sreyas-Sreelal/malluscript#14]
warning: field is never read: `src`
  --> src\lexer\mod.rs:18:5
   |
18 |     src: &'input str,
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `malluscript` (lib) generated 1 warning

**Comment by Sreyas-Sreelal** [comment]
Thanks :)
