### ISSUE TITLE
Fix error in lib.rs in src folder

### ISSUE THREAD

**Issue by Navaneethp007** [Sreyas-Sreelal/malluscript#23]
this struct takes 2 generic arguments but 1 generic argument was supplied
expected 2 generic argumentsrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fc%253A%2FUsers%2Fnvps7%2FOneDrive%2FDesktop%2FNVP%2520college%2FMallu%2Fmalluscript%2Fsrc%2Flib.rs)
lib.rs(41, 27): supplied 1 generic argument
lib.rs(587, 12): struct defined here, with 2 generic parameters: `H`, `I`
lib.rs(41, 29): add missing generic argument: `, I`

**Comment by Sreyas-Sreelal** [comment]
Hi,
could you explain what you are trying to do and how is it relevant to malluscript?

**Comment by Navaneethp007** [comment]
I am really sorry... it was actually a error from my side....I am really sorry
