### ISSUE TITLE
More formal language for Malluscript

### ISSUE THREAD

**Issue by Sreyas-Sreelal** [Sreyas-Sreelal/malluscript#30]
This project was initially started for the purpose of conducting an instant coding competition and just for fun, but it was never able to take place due to the COVID pandemic and other factors. I never expected it to receive so much public attention. Therefore, I am considering transitioning from the silly or comedic style of Malluscript to a more formal and proper version of Malayalam. For the sake of backward compatibility, I will keep the previous tokens for the time being, but I may remove them in future releases. Since Malayalam is a complex language, it may take some time to implement it correctly. I will use this issue as a reference for any development related to this matter. Anyone with a thorough understanding of Malayalam language and its grammar, even if they do not have a programming background, is welcome to review the development and their feedback would be greatly appreciated.

**Comment by Sreyas-Sreelal** [comment]
A new syntax for malluscript is being cooked in 1.0.0

OLD syntax 
```
പൊളിസാധനം നമ്പർ;
പൊളിസാധനം i;
പൊളിസാധനം കൊടി;

ദേ_പിടിച്ചോ "എന്റർ നമ്പർ : ";
നമ്പർ = നമ്പർ_താടാ;
i = 2;
കൊടി = 1;

റിപീറ്റടി i നെകാൾ (നമ്പർ/2)+1 വലുതാണെ {
    ശെരിയാണോ_മോനെ നമ്പർ%i ഉം 0 ഉം സെയിം_ആണേ {
        കൊടി = 0;
    }
    i = i+1;
}

ശെരിയാണോ_മോനെ കൊടി ഉം 0 ഉം സെയിം_ആണേ {
    ദേ_പിടിച്ചോ "Prime alle";
} ശെരി_അല്ലേൽ {
    ദേ_പിടിച്ചോ "Prime aane";
}
```
Same with new syntax will be 
```
കാണിക്കുക "എന്റർ നമ്പർ : ";
നമ്പർ = അക്കംവാങ്ങിക്കുക;
i = 2;
കൊടി = 1;

i നെകാൾ (നമ്പർ/2)+1 വലുതാണ് എങ്കിൽ ആവർത്തിക്കുക{
    നമ്പർ % i ഉം 0 ഉം തുല്യമാണ് എങ്കിൽ {
        കൊടി = 0;
    }
    i = i+1;
}

കൊടി ഉം 0 ഉം തുല്യമാണ് എങ്കിൽ {
    കാണിക്കുക "Prime alle";
} അതല്ലെങ്കിൽ {
    കാണിക്കുക "Prime aane";
}
```

Any feedback is welcome, and if any Malayalam pundits want to contribute they are more than welcome

**Comment by Sreyas-Sreelal** [comment]
I have removed previous declaration statements, since I can't think of any proper Malayalam verb to describe that and also it feels like redundant now that I think of it. Variables from `1.0.0` will get automatically allocated to symbol table without needing declaration statement.

**Comment by Sreyas-Sreelal** [comment]
Also the style of conditional statements and loops is also redefined to fit in more meaningful way when expressed in Malayalam.

**Comment by subins2000** [comment]
One feedback I have is to agglutinate words where possible ([agglutination](https://ml.wikipedia.org/wiki/%E0%B4%85%E0%B4%97%E0%B5%8D%E0%B4%B2%E0%B5%82%E0%B4%9F%E0%B5%8D%E0%B4%9F%E0%B4%BF%E0%B4%A8%E0%B5%87%E0%B4%B7%E0%B5%BB_(%E0%B4%AD%E0%B4%BE%E0%B4%B7%E0%B4%BE%E0%B4%B6%E0%B4%BE%E0%B4%B8%E0%B5%8D%E0%B4%A4%E0%B5%8D%E0%B4%B0%E0%B4%82)) is one of the key features of Malayalam):

```ruby
കൊടി ഉം 0 ഉം തുല്യമാണെങ്കിൽ {
  // ==
}

കൊടി ഉം 0 ഉം തുല്യമല്ലെങ്കിൽ {
  // !=
}

കൊടി 0 ത്തേക്കാൾ വലുതാണെങ്കിൽ {
  // കൊടി >= 0
}

കൊടി 0 ത്തേക്കാൾ ചെറുതാണെങ്കിൽ {
  // കൊടി <= 0
}

0 കൊടി യേക്കാൾ വലുതാണെങ്കിൽ {
  // 0 >= കൊടി
}
```

**Comment by subins2000** [comment]
One other possibility of agglutination is syntax like this:

```ruby
കൊടിയും പൂജ്യവും തുല്യമാണെങ്കിൽ {
  // കൊടി == 0
}

കൊടി പതിനഞ്ചിനേക്കാൾ വലുതാണെങ്കിൽ {
  // കൊടി >= 15
}

കൊടി ഇരുപതിനേക്കാൾ വലുതാണെങ്കിൽ {
  // കൊടി >= 20
}
```

You can perhaps integrate [mlmorph](https://morph.smc.org.in/analyser.html) to convert the Malayalam numeral word to number but this might make the compile time slower (I'm not sure though) but this'd be a good practical usecase of Malayalam morphological analysis.

<img width="765" alt="Screenshot 2023-05-16 at 6 32 26 PM" src="https://github.com/Sreyas-Sreelal/malluscript/assets/2305675/a1a61d6e-48ad-43d2-9b0c-5ed5e9335e01">

<img width="750" alt="Screenshot 2023-05-16 at 6 29 57 PM" src="https://github.com/Sreyas-Sreelal/malluscript/assets/2305675/d28746d5-cf0e-4a42-b858-41510f840758">

<img width="757" alt="Screenshot 2023-05-16 at 6 28 46 PM" src="https://github.com/Sreyas-Sreelal/malluscript/assets/2305675/ed18cd86-67b5-49c7-951d-3e8c29b5d49c">

**Comment by Sreyas-Sreelal** [comment]
mlmorph looks great!, thank you for sharing it :) Though I'm not sure if I will integrate it into the lexer for `1.0.0`, but it is definitely worth a look for future versions, probably will try writing a Rust bindings for mlmorph as well if it's there none yet :)

**Comment by Sreyas-Sreelal** [comment]
Thank you @subins2000 I have added agglutination for conditional statements in d92c2b0. Currently I have added new keyword tokens and added separate grammar for parsing it. I will hackaround, if there's any better solution exists that can be used by the others incase they want to add  new syntax similar to it :)

**Comment by AndrewBastin** [comment]
@subins2000 @Sreyas-Sreelal, just out of curiosity, one of the things as Subin said is cool with Malayalam is agglutination.

Taking a page from NLP, can the language grammar be written to break these into root words and then write the lexer to process on just those root words ? Like a pre-processing step before the tokenization happens.

That would make it easy to handle various cases like this which is inevitable.

I tried running this endpoint https://hopp.sh/r/tw29IBJe34RW (yes, shameless plug 😅) and used the `$.[0].[*].root` JSON filter and it generated consistent root words for a lot of variations for the same input word.

I have no idea if this will even work, but if the language could somehow handle these sorts of cases, it would be kinda cool ngl.

**Comment by Sreyas-Sreelal** [comment]
@AndrewBastin yes that's the idea, passing the written program through mlmorph to normalize or break down before feeding it to lexer for tokenization, that should work without needing much effort in changing the lexer,parser or executor. But my major concern, as @subins2000 said, is performance (although it shouldn't matter since it only affect the performance of tokenisation and won't affect the execution), but either way if we can achieve it that will be game changing :)
