### ISSUE TITLE
പൊളിസാനം - Normalise Keywords

### ISSUE THREAD

**Issue by mujeebcpy** [Sreyas-Sreelal/malluscript#5]
പൊളിസാധനം എന്നാണ് മലയാളമെങ്കിലും ഹിറ്റായ ഐറ്റം പൊളിസാനം എന്ന നാടൻ പ്രയോഗമാണ്. വേണമെങ്കില്‍ pwoli_sanam എന്നാക്കാവുന്നതാണ്

**Comment by Sreyas-Sreelal** [comment]
Done.I've also normalised other keywords too.
https://github.com/Sreyas-Sreelal/malluscript/blob/master/src/lexer/keywords.rs#L10-L36

**Comment by Sreyas-Sreelal** [comment]
I think i'll leave this open,because there could be more keywords that can be normalised.

**Comment by theapache64** [comment]
> Done.I've also normalised other keywords too.
> https://github.com/Sreyas-Sreelal/malluscript/blob/master/src/lexer/keywords.rs#L10-L36

Kidu implementation :+1:

**Comment by Sreyas-Sreelal** [comment]
Closing this in favor of #30
