### ISSUE TITLE
Using veluthane

### ISSUE THREAD

**Issue by servusdei** [Sreyas-Sreelal/malluscript#8]
@Sreyas-Sreelal  veluthane യൂസ് ചെയ്യുന്നതിനേക്കാൾ   valuthanenkil യൂസ് ചെയ്യുന്നത് കുറച്ചു കൂടി അർത്ഥം കിട്ടും

**Comment by de-sh** [comment]
@Sreyas-Sreelal I believe we need to create an RFC list. Such corrections will keep on coming in and it's best that we make full use of the opportunity.

**Comment by servusdei** [comment]
What is an RFC list? @de-sh

**Comment by de-sh** [comment]
@Danielabraham7, when one creates a language it is necessary that you must also take inputs from people who are probably going to develop with it. And that's not necessary for an esoteric language, but you must also consider the growing interest among developers for malluscript.

rust-lang has an awesome [RFC archive](https://github.com/rust-lang/rfcs) if you'd like to consider it.

**Comment by servusdei** [comment]
Ok  @de-sh Thanks for replying.

**Comment by Sreyas-Sreelal** [comment]
I think an RFC list is not necessary for now,as I believe the user base is still very low,it's an esoteric   
 language and most of all the language  has very small amount of semantics and keywords.May be in future when the community around this get large and may be the language gets more complicated and serious.

**Comment by Sreyas-Sreelal** [comment]
Added variants for `veluthane` and `cheruthane` 
Closing this in favour of #5
